version: '3.8'

services:
#  redis:
#    image: redis:7
#    container_name: happyBD_redis
#    ports:
#      - 6379:6379


  rabbitmq:
    image: "rabbitmq:management"  # используем образ с включенным управлением
    hostname: "rabbitmqhost"
    restart: always
    ports:
      - "5672:5672"  # порт для AMQP
      - "15672:15672"  # порт для управляющего интерфейса
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - .env
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 1431655766  # 1.3 Gib
#    depends_on:
#      - redis

